services:
  - type: web
    name: backend-inventario
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DB_HOST
        value: mysql-emca              # 👈 nombre del servicio MySQL en Render
      - key: DB_PORT
        value: 3306
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: jara123
      - key: DB_NAME
        value: inventarioPc           # 👈 nombre de la base de datos creada en schema.sql
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://front-inventario-grande-rvef.vercel.app
